LOCATION_PRESETS = [
    {
        "category": "Observatoires en France",
        "name": "Telescope T1m - Observatoire de Meudon",
        "latitude": 48.805,
        "longitude": 2.23006,
    },
    {
        "category": "Observatoires en France",
        "name": "Observatoire de Paris",
        "latitude": 48.8366,
        "longitude": 2.3369,
    },
    {
        "category": "Observatoires en France",
        "name": "Observatoire de Nice",
        "latitude": 43.7279,
        "longitude": 7.2995,
    },
    {
        "category": "Observatoires en France",
        "name": "Observatoire du Pic du Midi",
        "latitude": 42.9369,
        "longitude": 0.1426,
    },
    {
        "category": "Observatoires en France",
        "name": "Observatoire de Haute-Provence",
        "latitude": 43.9317,
        "longitude": 5.7122,
    },
    {
        "category": "Observatoires en France",
        "name": "Observatoire de Strasbourg",
        "latitude": 48.5839,
        "longitude": 7.7681,
    },
    {
        "category": "Observatoires en France",
        "name": "Observatoire de Bordeaux",
        "latitude": 44.8350,
        "longitude": -0.5270,
    },
    {
        "category": "Observatoires en France",
        "name": "Station de radioastronomie de Nancay",
        "latitude": 47.3800,
        "longitude": 2.1960,
    },
    {
        "category": "Capitales europeennes",
        "name": "Amsterdam",
        "latitude": 52.3676,
        "longitude": 4.9041,
    },
    {"category": "Capitales europeennes", "name": "Andorre-la-Vieille", "latitude": 42.5063, "longitude": 1.5218},
    {"category": "Capitales europeennes", "name": "Ankara", "latitude": 39.9334, "longitude": 32.8597},
    {"category": "Capitales europeennes", "name": "Athenes", "latitude": 37.9838, "longitude": 23.7275},
    {"category": "Capitales europeennes", "name": "Belgrade", "latitude": 44.8125, "longitude": 20.4612},
    {"category": "Capitales europeennes", "name": "Berlin", "latitude": 52.5200, "longitude": 13.4050},
    {"category": "Capitales europeennes", "name": "Berne", "latitude": 46.9480, "longitude": 7.4474},
    {"category": "Capitales europeennes", "name": "Bratislava", "latitude": 48.1486, "longitude": 17.1077},
    {"category": "Capitales europeennes", "name": "Bruxelles", "latitude": 50.8503, "longitude": 4.3517},
    {"category": "Capitales europeennes", "name": "Bucarest", "latitude": 44.4268, "longitude": 26.1025},
    {"category": "Capitales europeennes", "name": "Budapest", "latitude": 47.4979, "longitude": 19.0402},
    {"category": "Capitales europeennes", "name": "Chisinau", "latitude": 47.0105, "longitude": 28.8638},
    {"category": "Capitales europeennes", "name": "Copenhague", "latitude": 55.6761, "longitude": 12.5683},
    {"category": "Capitales europeennes", "name": "Dublin", "latitude": 53.3498, "longitude": -6.2603},
    {"category": "Capitales europeennes", "name": "Helsinki", "latitude": 60.1699, "longitude": 24.9384},
    {"category": "Capitales europeennes", "name": "Kiev", "latitude": 50.4501, "longitude": 30.5234},
    {"category": "Capitales europeennes", "name": "Lisbonne", "latitude": 38.7223, "longitude": -9.1393},
    {"category": "Capitales europeennes", "name": "Ljubljana", "latitude": 46.0569, "longitude": 14.5058},
    {"category": "Capitales europeennes", "name": "Londres", "latitude": 51.5074, "longitude": -0.1278},
    {"category": "Capitales europeennes", "name": "Luxembourg", "latitude": 49.6116, "longitude": 6.1319},
    {"category": "Capitales europeennes", "name": "Madrid", "latitude": 40.4168, "longitude": -3.7038},
    {"category": "Capitales europeennes", "name": "Monaco", "latitude": 43.7384, "longitude": 7.4246},
    {"category": "Capitales europeennes", "name": "Oslo", "latitude": 59.9139, "longitude": 10.7522},
    {"category": "Capitales europeennes", "name": "Paris", "latitude": 48.8566, "longitude": 2.3522},
    {"category": "Capitales europeennes", "name": "Prague", "latitude": 50.0755, "longitude": 14.4378},
    {"category": "Capitales europeennes", "name": "Reykjavik", "latitude": 64.1466, "longitude": -21.9426},
    {"category": "Capitales europeennes", "name": "Riga", "latitude": 56.9496, "longitude": 24.1052},
    {"category": "Capitales europeennes", "name": "Rome", "latitude": 41.9028, "longitude": 12.4964},
    {"category": "Capitales europeennes", "name": "Stockholm", "latitude": 59.3293, "longitude": 18.0686},
    {"category": "Capitales europeennes", "name": "Tallinn", "latitude": 59.4370, "longitude": 24.7536},
    {"category": "Capitales europeennes", "name": "Tirana", "latitude": 41.3275, "longitude": 19.8187},
    {"category": "Capitales europeennes", "name": "Vaduz", "latitude": 47.1410, "longitude": 9.5209},
    {"category": "Capitales europeennes", "name": "Varsovie", "latitude": 52.2297, "longitude": 21.0122},
    {"category": "Capitales europeennes", "name": "Vienne", "latitude": 48.2082, "longitude": 16.3738},
    {"category": "Capitales europeennes", "name": "Vilnius", "latitude": 54.6872, "longitude": 25.2797},
    {"category": "Capitales europeennes", "name": "Zagreb", "latitude": 45.8150, "longitude": 15.9819},
    {"category": "Chefs-lieux en France", "name": "Ajaccio", "latitude": 41.9192, "longitude": 8.7386},
    {"category": "Chefs-lieux en France", "name": "Amiens", "latitude": 49.8941, "longitude": 2.2958},
    {"category": "Chefs-lieux en France", "name": "Besancon", "latitude": 47.2378, "longitude": 6.0241},
    {"category": "Chefs-lieux en France", "name": "Bordeaux", "latitude": 44.8378, "longitude": -0.5792},
    {"category": "Chefs-lieux en France", "name": "Caen", "latitude": 49.1829, "longitude": -0.3707},
    {"category": "Chefs-lieux en France", "name": "Clermont-Ferrand", "latitude": 45.7772, "longitude": 3.0870},
    {"category": "Chefs-lieux en France", "name": "Dijon", "latitude": 47.3220, "longitude": 5.0415},
    {"category": "Chefs-lieux en France", "name": "Fort-de-France", "latitude": 14.6161, "longitude": -61.0588},
    {"category": "Chefs-lieux en France", "name": "Lille", "latitude": 50.6292, "longitude": 3.0573},
    {"category": "Chefs-lieux en France", "name": "Limoges", "latitude": 45.8336, "longitude": 1.2611},
    {"category": "Chefs-lieux en France", "name": "Lyon", "latitude": 45.7640, "longitude": 4.8357},
    {"category": "Chefs-lieux en France", "name": "Marseille", "latitude": 43.2965, "longitude": 5.3698},
    {"category": "Chefs-lieux en France", "name": "Metz", "latitude": 49.1193, "longitude": 6.1757},
    {"category": "Chefs-lieux en France", "name": "Montpellier", "latitude": 43.6110, "longitude": 3.8767},
    {"category": "Chefs-lieux en France", "name": "Nantes", "latitude": 47.2184, "longitude": -1.5536},
    {"category": "Chefs-lieux en France", "name": "Orleans", "latitude": 47.9029, "longitude": 1.9093},
    {"category": "Chefs-lieux en France", "name": "Paris", "latitude": 48.8566, "longitude": 2.3522},
    {"category": "Chefs-lieux en France", "name": "Poitiers", "latitude": 46.5802, "longitude": 0.3404},
    {"category": "Chefs-lieux en France", "name": "Rennes", "latitude": 48.1173, "longitude": -1.6778},
    {"category": "Chefs-lieux en France", "name": "Rouen", "latitude": 49.4432, "longitude": 1.0993},
    {"category": "Chefs-lieux en France", "name": "Saint-Denis de La Reunion", "latitude": -20.8789, "longitude": 55.4481},
    {"category": "Chefs-lieux en France", "name": "Strasbourg", "latitude": 48.5734, "longitude": 7.7521},
    {"category": "Chefs-lieux en France", "name": "Toulouse", "latitude": 43.6047, "longitude": 1.4442},
]


def preset_label(preset):
    return f"{preset['category']} - {preset['name']}"
